### PR TITLE
Fix undefined descriptions

### PR DESCRIPTION
**Pull request by mpolidori**

### CODE REVIEW

**Comment by Mikanebu** [comment]
@mpolidori But this PR affects to this PR from @Dragan Avramovic https://github.com/datopian/frontend-oddk/pull/64, where he fixed markdown description. Could you double check, please. 
This part of showcase page changed by previous PR, then you reverted back, I can merge PR, and test on dev, if you want, let me know
```
{{ dataset.notes_translated[locale] or dataset.description | processMarkdown | safe }}
```

**Comment by mpolidori** [comment]
@Mikanebu Ah, I see what you mean. I've pushed a change, as well as adding the same thing to the search page. This should resolve the problem.

**Comment by Mikanebu** [comment]
Thanks! Looks good for me.

**Review by Mikanebu — APPROVED** [review]
Good

**Comment by Mikanebu** [comment]
@mpolidori  Could you release new v1.0.12? So I can update dev and prod with the fix

**Pull request merged**
