### PR TITLE
WCAG 2.1 full A compliance

### PR DESCRIPTION
**Pull request by mpolidori**
Changes for WCAG 2.1 A conformance.

### CODE REVIEW

**Comment by mpolidori** [comment]
@EvgeniiaVak Do you think you could review this in the morning tomorrow? I know it's quite a big PR. If not, just let me know.

**Comment by mpolidori** [comment]
@EvgeniiaVak And another thing I want to mention is that I'm aware that editing the chunk files is bad practice. I spoke with Osahon about it and he said to just do this. I'm not sure what the odds are that the chunk files will get rebuilt in the future, but it sounds unlikely.

**Comment by EvgeniiaVak** [comment]
@mpolidori you right, chunk files should not be edited. The probability of data-explorer being updated is pretty high - the repo is ours, it's here https://github.com/datopian/data-explorer. If any changes need to be applied to data explorer, please update there and create a new build, we have docs about how-to here https://tech.datopian.com/data-explorer/#new-builds

**Comment by EvgeniiaVak** [comment]
@mpolidori Please test that on a dataset page links to previews work (they are based on elements ids, in case you changed something there):

image

**Review by EvgeniiaVak — CHANGES_REQUESTED** [review]
@mpolidori if you have any questions about data-explorer you can ping me (or Dragan / Sagar / Anuar)

**Comment by mpolidori** [comment]
> @mpolidori you right, chunk files should not be edited. The probability of data-explorer being updated is pretty high - the repo is ours, it's here https://github.com/datopian/data-explorer. If any changes need to be applied to data explorer, please update there and create a new build, we have docs about how-to here https://tech.datopian.com/data-explorer/#new-builds

This I did not know. Osahon and I were basing this thought on a previous project he worked on with data-explorer, which may have been using the ofkn version?

**Comment by mpolidori** [comment]
> @mpolidori Please test that on a dataset page links to previews work (they are based on elements ids, in case you changed something there):
> 
> image

This is exactly what I need to change. IDs must be unique or WCAG is not compliant. I didn't know that previews were linked to this... so, I will look at it in a bit, but do you think there's a clean way to ensure all IDs are unique?

**Comment by mpolidori** [comment]
@EvgeniiaVak I reverted the chunk changes, so this PR should be ready now. I believe that all other changes need to be implemented in data-explorer

**Comment by EvgeniiaVak** [comment]
> This I did not know. Osahon and I were basing this thought on a previous project he worked on with data-explorer, which may have been using the ofkn version?

@mpolidori Sorry, I don't know anything about okfn version.

**Comment by EvgeniiaVak** [comment]
> This is exactly what I need to change. IDs must be unique or WCAG is not compliant. I didn't know that previews were linked to this... so, I will look at it in a bit, but do you think there's a clean way to ensure all IDs are unique?

@mpolidori it is fine to change the IDs the way you did - the main thing that the buttons work 👍

**Comment by EvgeniiaVak** [comment]
> @EvgeniiaVak I reverted the chunk changes, so this PR should be ready now. I believe that all other changes need to be implemented in data-explorer

@mpolidori yes, and then build the new version there, copy the build here (to oddk theme) and test that it works and didn't break anything else - browse the pages to check that everything's working (there might have been other changes since the last update) and I don't think we have autotests for oddk yet. I agree you can leave it for another PR, I'm merging this one.

**Review by EvgeniiaVak — APPROVED** [review]

**Pull request merged**
